output: revision-1.yaml
metadata:
  appVersion: update-demo-r1-onboard
rosModules:
  companion-analytics:
    image: cloud-native-ros/companion-analytics:dev
    preference: [onboard]
rosParamMap:
  companion-analytics-config-drone01:
    data:
      processing_mode: onboard
      processing_delay_ms: "220"
      latency_slo_ms: "150"
