#!/usr/bin/env python3
"""S2's cluster configuration: E0's, plus k3s's network policy controller disabled
(--disable-network-policy on the server). S2 only (Viviana, 1 October 2026;
docs/S2_NETPOL_BENCH_PREREGISTRATION.md).

  render_s2_k3d_config.py E0_CONFIG OUT

Why: the controller (kube-router) periodically re-inserts its own jumps at the head of
INPUT/OUTPUT/FORWARD; during a cut that pushes S2's partition jump to the second place and
fails Q3_hold, on SQLite and on etcd alike, with the traffic still blocked
(results/evidence/runs/ETCD_DIAGNOSIS.md, D3). With the controller disabled on a fresh
cluster no KUBE-ROUTER rule appears (S2_NETPOL_DIAGNOSIS.md, ETCD_TARGETED_TESTS.md). The
bench applies no NetworkPolicy, so nothing else changes. k3s documents that disabling it on
an existing cluster leaves the rules already created: a fresh cluster each time.

The output is checked, not just written: parsed, it must equal E0's configuration with
exactly that one argument added, on server:0.
"""

import copy
import sys

import yaml

ARG = {"arg": "--disable-network-policy", "nodeFilters": ["server:0"]}
MARKER = "    extraArgs:\n"


def render(e0_text):
    if e0_text.count(MARKER) != 1:
        raise ValueError(f"E0's configuration has {e0_text.count(MARKER)} extraArgs blocks, expected 1")
    out = e0_text.replace(MARKER, MARKER + '      - arg: "--disable-network-policy"\n'
                                           '        nodeFilters: ["server:0"]\n')
    expected = copy.deepcopy(yaml.safe_load(e0_text))
    expected["options"]["k3s"]["extraArgs"].insert(0, ARG)
    if yaml.safe_load(out) != expected:
        raise ValueError("rendered configuration is not E0's plus --disable-network-policy")
    return out


def main(src, dst):
    out = render(open(src).read())
    with open(dst, "w") as h:
        h.write("# generated by scripts/render_s2_k3d_config.py from " + src + "\n" + out)
    return 0


if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:3]))
