# Generated by Django 3.2.18 on 2026-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='revision',
            field=models.PositiveIntegerField(default=1, help_text='Last successfully applied deployment manifest revision.'),
        ),
        migrations.AddField(
            model_name='deploymentevent',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deploymentevent',
            name='target_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
