apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-native-application-manager
  namespace: ros-default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-native-application-manager
  namespace: ros-default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-native-application-manager
  namespace: ros-default
subjects:
- kind: ServiceAccount
  name: cloud-native-application-manager
  namespace: ros-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-native-application-manager
